databases:
  - name: database
    databaseName: ticket_event
    user: facil_facil_hospedagem

services:
  - type: web
    name: ticket_event
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false