default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ticket_event_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: ticket_event_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: ticket_event_production
  username: ticket_event
  password: <%= ENV["DEVELOPER_EVOLUTION_DATABASE_PASSWORD"] %>
