default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ticket_event_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: ticket_event_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: <%= ENV['DB_URL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>