name: "Ruby on Rails CI"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ticket_event_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/ticket_event_test"
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Font Minimagick
        run: apt install -y libfreetype6-dev gsfonts libmagickwand-dev imagemagick
      - name: Build Tailwind
        run: |
          npm install esbuild
          bin/rails tailwindcss:build
      - name: Set up database schema
        run: bin/rails db:migrate
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: bin/rake
#
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Install Ruby and gems
#        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
#        with:
#          bundler-cache: true
#      # Add or replace any other lints here
#      - name: Security audit dependencies
#        run: bin/bundler-audit --update
#      - name: Security audit application code
#        run: bin/brakeman -q -w2
#      - name: Lint Ruby files
#        run: bin/rubocop --parallel
