name: "Ruby on Rails CI"
on:
  pull_request:
    branches:
      - main
      - 'release/*'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ticket_event_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/ticket_event_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ticket_event
      - name: Set up database schema
        run: docker run --network host -e DATABASE_URL=postgres://rails:password@localhost:5432/ticket_event_test ticket_event bin/rails db:migrate
      - name: Run Tests
        run: docker run --network host -e DATABASE_URL=postgres://rails:password@localhost:5432/ticket_event_test ticket_event bin/rake
        env:
          GITHUB_KEY: ${{ secrets.API_GITHUB_KEY }}
#
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Install Ruby and gems
#        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
#        with:
#          bundler-cache: true
#      # Add or replace any other lints here
#      - name: Security audit dependencies
#        run: bin/bundler-audit --update
#      - name: Security audit application code
#        run: bin/brakeman -q -w2
#      - name: Lint Ruby files
#        run: bin/rubocop --parallel
